language: csharp
branches:
  except:
  - /^[0-9]/
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
matrix:
  include:
    - os: linux
      dotnet: 2.1.301
    - os: osx 
      osx_image: xcode9 # OSX 10.12
      dotnet: 2.1.301
      before_install:
        - ulimit -n 4096
script:
  - dotnet restore
  - dotnet build --configuration Release
  - dotnet test test/Winton.Extensions.Serialization.Json.Tests/ --no-build --configuration Release --framework netcoreapp2.1
notifications:
  on_success: always
  on_failure: always
  on_start: always